import type { Metadata } from 'next';
import { Rubik, Raleway } from 'next/font/google';
import '../../globals.css';
import Logo from '@public/BeTorrent.svg';

const rubik = Rubik({
  subsets: ['latin'],
  weight: ['300', '400', '500', '700', '800', '900', '600'],
  variable: '--font-rubik',
});

const raleway = Raleway({
  subsets: ['latin'],
  weight: ['300', '400', '500', '700', '800', '900', '600'],
  variable: '--font-raleway',
});

export const metadata: Metadata = {
  title: 'BeTorrent',
  description: 'Generated by create next app', // to add a meaningful description
  icons: [{ rel: 'icon', url: Logo.src }],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' className={`${rubik.variable} ${raleway.variable}`}>
      <body>{children}</body>
    </html>
  );
}
